default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ttdb_dev
  username: ttdb_user
  password: <%= ENV['TTDB_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: ttdb_test
  username: ttdb_user
  password: <%= ENV['TTDB_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: ttdb
  username: ttdb_user
  password: <%= ENV['TTDB_DATABASE_PASSWORD'] %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
